### ISSUE TITLE
fabricService.get("key") 报错 "status": -505

### ISSUE THREAD

**Issue by tangsng** [ecsoya/spring-fabric-gateway#6]
{
    "status": -505,
    "errorMsg": "org.hyperledger.fabric.sdk.exception.ProposalException: java.lang.NullPointerException",
    "transactionId": null,
    "data": null,
    "metadata": null,
    "ok": false
}

**Comment by ecsoya** [comment]
你把详细的问题描述一下

**Comment by tangsng** [comment]
基于fabric-demo这个项目：
1、首先调用
@GetMapping("/add")
public FabricResponse add(FabricObject object) {
	return fabricService.create(object);
}

添加了一条如下数据：
{"data":[{"id":"1625054894897","type":"demo2","values":{"author":"Ecsoya","time":"Wed Jun 30 2021 20:08:14 GMT+0800 (中国标准时间)","timestamp":"1625054894897","type":"demo2","value":"123ww"}}],"recordsCount":1,"bookmark":"g1AAAABseJzLYWBgYMpgSmHgKy5JLCrJTq2MT8lPzkzJBYrLMZRUFqTWAcUYUlJz840YDM2MTA1MTSwsgcicAaSLA6aLCPVZAElpHRk","pageSize":10,"recordsTotal":1,"recordsFiltered":1,"currentPage":0}


2、想根据“key”调用方法查询得到这条数据（我理解id即为key：http://localhost:8081/get?type=demo2&id=1625054894897）
@GetMapping("/get")
public FabricQueryResponse<FabricObject> get(FabricObject object) {
	return fabricService.get(object.getId());
}


3、报错如下：
![image](https://user-images.githubusercontent.com/30173491/124450050-a2cc0c80-ddb6-11eb-9707-af478c209557.png)

**Comment by ecsoya** [comment]
你用这个方法 **fabricService.get(object.getId(), object.getType());** 试一下，fabricService.get(id)会自动识别type，可能会出错

**Comment by tangsng** [comment]
fabricService.get(object.getId(), object.getType()) 确实可行，谢谢！
